
--Data Prep to create Student Data

select * from  HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS limit 10;

desc table HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS;

select  REPLACE(DONOR_ID, 'DONOR_', 'STUDENT_') as STUDENT_ID, FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, LATITUDE, LONGITUDE,   CASE (ABS(RANDOM()) % 3) + 1
        WHEN 1 THEN 'Chemistry'
        WHEN 2 THEN 'Engineering'
        WHEN 3 THEN 'Accounting'
    END AS MAJOR from  HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS where MAJOR is null limit 20;

select Major, count(*) from HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS group by 1 order by 2 desc;

 drop table HIGHER_ED_DEMO.STUDENT.ENROLLED_STUDENTS;
create or replace  table HIGHER_ED_DEMO.STUDENT.STUDENT as 
select  REPLACE(DONOR_ID, 'DONOR_', 'STUDENT_') as STUDENT_ID, FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP_CODE, LATITUDE, LONGITUDE,   CASE (ABS(RANDOM()) % 3) + 1
        WHEN 1 THEN 'Chemistry'
        WHEN 2 THEN 'Engineering'
        WHEN 3 THEN 'Accounting'
    END AS MAJOR, 'Enrolled' as STUDENT_STATUS from  HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS where MAJOR is null limit 20;





select first_name, last_name, full_name from HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS where zip_code = '29650' and full_name is null;
select first_name, last_name, full_name from HIGHER_ED_DEMO.ALUMNI_TARGETING.ALUMNI_DONORS where zip_code = '29650' and full_name is null;


--HIGHER_ED_DEMO.STUDENT.ENROLLED_STUDENTS

alter table HIGHER_ED_DEMO.STUDENT.STUDENT add column
H3_LEVEL_7 VARCHAR(20),
    H3_LEVEL_8 VARCHAR(20),
    H3_LEVEL_9 VARCHAR(20);


update HIGHER_ED_DEMO.STUDENT.STUDENT set H3_LEVEL_7 =  H3_LATLNG_TO_CELL_STRING(LATITUDE, LONGITUDE, 7);
update HIGHER_ED_DEMO.STUDENT.STUDENT set H3_LEVEL_8 =  H3_LATLNG_TO_CELL_STRING(LATITUDE, LONGITUDE, 8);
update HIGHER_ED_DEMO.STUDENT.STUDENT set H3_LEVEL_8 =  H3_LATLNG_TO_CELL_STRING(LATITUDE, LONGITUDE, 9);



alter table HIGHER_ED_DEMO.STUDENT.STUDENT add column
ANNUAL_DONATION_AMOUNT NUMBER(10,2),
CUMULATIVE_DONATION_AMOUNT NUMBER(12,2);
     
update HIGHER_ED_DEMO.STUDENT.STUDENT set 
 ANNUAL_DONATION_AMOUNT = 100,
 CUMULATIVE_DONATION_AMOUNT = 300;
-- create h3
 


